### ISSUE TITLE
Responsive Navbar with Hamburger Menu

### ISSUE THREAD

**Issue by Komachian** [Anwesha-2k23/frontend#10]
Create a responsive navbar with hamburger menu to be displayed on smaller displays. The design of the navbar and the concept design of the hamburger menu have been attached.
- [ ] All the assets required for this issue have been provided inside `public/navbar`
- [ ] Font to be used is `Poppins`
- [ ] Add entries `CA`, `Multicity`, `Gallery`, and `Login` for now
- [ ] The hamburger icon (≡) should be displayed on the left side of the navbar in place of the mandala on the left, to be displayed only when the screen size falls below a certain width
- [ ]  Hamburger menu should have same background colour  - dark blue (#4E1DD9) - as of the navbar border

### Instructions
- Create a new `navbar.js` file inside the `components` directory
- Create the responsive navbar with hamburger menu component with functionality as described above
- Ensure responsiveness is maintained well
- **Only make the pull request to the `main` branch** of the [`Anwesha-2k23/frontend`](https://github.com/Anwesha-2k23/frontend) repository
- Add video-snippets/screenshots when creating the pull request to showcase the responsiveness
 
![Navbar](https://user-images.githubusercontent.com/75087669/205893599-f9c0ea32-eb19-49c3-b90e-601358bd1e80.svg)
![Hamburger Menu](https://user-images.githubusercontent.com/75087669/205880669-1a4845e8-6f47-4941-9978-927e7da12069.png)

**Comment by Tushar98644** [comment]
assign me...

**Comment by ghost** [comment]
I would like to contribute in this

**Comment by himanshu1221** [comment]
i would like to contribute in it under codepeak and kwoc22 would be glad if u assign me in it

**Comment by Komachian** [comment]
I'm assigning this to @Tushar98644, since he approached first

**Comment by HimanshuTembhe** [comment]
Can you assign me this issue ?

**Comment by Komachian** [comment]
@HimanshuTembhe currently @Tushar98644 has been assigned this issue
