### ISSUE TITLE
Add Animations on Scroll to the Gallery Sections

### ISSUE THREAD

**Issue by Komachian** [Anwesha-2k23/frontend#13]
Add simple animations to the gallery page
- [ ]  Add animations, so that each section in the gallery slides in from the side, as we scroll downwards
- [ ]  Animations should not be too over the top
- [ ]  By 'section' we refer to event title, short description and all images pertaining to the event
- [ ]  Approach on-scroll animation functionality from a Javascript point of view rather than CSS

### Instructions
- Refer the `gallery.js` file inside the `pages` directory
- Add animation as described above
- Ensure responsiveness is maintained well
- **Only make the pull request to the `main` branch** of the [`Anwesha-2k23/frontend`](https://github.com/Anwesha-2k23/frontend) repository
- Add video-snippets/screenshots when creating the pull request to showcase the responsiveness

![image](https://user-images.githubusercontent.com/75087669/206170286-35634107-757c-4ae1-a6da-b9364ae08f8b.png)

**Comment by ghost** [comment]
@Komachian assign this to me

**Comment by Komachian** [comment]
You can proceed 👍🏽

**Comment by Komachian** [comment]
@itz-deepak Do note that a new PR was merged in this section very recently. Hence, you **might want to pull from origin** before working any further.
