### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by Komachian** [Anwesha-2k23/frontend#8]
CODEPEAK’s own leader board design (mobile view) has been attached for reference (only for inspiration). Pagination may not be required considering that number of participants would be pretty less. After completion of the task, create a pull request to the `main` branch of the `frontend` repository.

- [ ]  Table with columns - Position, Name, College, Points
- [ ]  Search functionality - matches both name and college simultaneously
- [ ]  Background of the page need not be focused upon at this stage - a simple contrasting single coloured background would do. No navbar required either.

### Instructions
- Create a new `leaderboard.js` file inside the `pages` directory
- Create the leader board with functionality as described above
- Ensure responsiveness is maintained well
- **Only make the pull request to the `main` branch** of the [`Anwesha-2k23/frontend`](https://github.com/Anwesha-2k23/frontend) repository
- Add video-snippets/screenshots when creating the pull request to showcase the responsiveness

![Leaderboard](https://user-images.githubusercontent.com/75087669/205919152-b18f6717-8fb4-4f70-aff6-5d4a5c22706c.png)

**Comment by AaryaaRam** [comment]
@Komachian 
I would like to work on this issue!!

**Comment by Komachian** [comment]
Go ahead!

**Comment by Komachian** [comment]
Go ahead!

**Comment by AaryaaRam** [comment]
Sir could you please elaborate on what you meant when you said " Search functionality - matches both name and college simultaneously"

**Comment by Komachian** [comment]
Let's say you type 'Aaryaa' in the search bar, in that case in the search results both the participant 'Aaryaa Ram' should be displayed as well as any participant from 'Aaryaa College of Sciences'.
