### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by Komachian** [Anwesha-2k23/frontend#9]
Create a simple gallery page based on the wire frame attached.
- [ ]  Seperate the gallery into multiple events as given in the wire frame
- [ ]  Each event should have a title and short description followed by the images displayed as shown in the wire frame
- [ ]  The events and their titles, short description and images should be rendered from JSON (you can hard code it for now)

### Instructions
- Create a new `gallery.js` file inside the `pages` directory
- Create the gallery page with functionality as described above
- Ensure responsiveness is maintained well
- **Only make the pull request to the `main` branch** of the [`Anwesha-2k23/frontend`](https://github.com/Anwesha-2k23/frontend) repository
- Add video-snippets/screenshots when creating the pull request to showcase the responsiveness

![Gallery](https://user-images.githubusercontent.com/75087669/205865624-108de3bc-0982-4235-a21c-a1d2843e2598.png)

**Comment by Adittya-Gupta** [comment]
I think I can solve this issue. Kindly assign it to me

**Comment by Komachian** [comment]
Move forward!

**Comment by Dibyendu303** [comment]
Hey @Komachian I worked on this issue and fixed the image layout as you wanted. Should I create a pull request?
Attached a video preview.


https://user-images.githubusercontent.com/66685553/206161430-fe1e9e34-5014-4840-a7f4-674928b6f75a.mp4

**Comment by Komachian** [comment]
@Dibyendu303 that looks really good!! Please do create the pull request. Before that though, you may need to pull from origin once since, @Adittya-Gupta's PR was merged a few hours ago.

**Comment by Dibyendu303** [comment]
Sure, will do.
